version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: bms-mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - bms-net
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log

  influxdb:
    image: influxdb:2.7
    container_name: bms-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    networks:
      - bms-net
    volumes:
      - ./docker/influxdb/data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}

  grafana:
    image: grafana/grafana-oss:latest
    container_name: bms-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - bms-net
    volumes:
      - ./docker/grafana/data:/var/lib/grafana

  postgres:
    image: postgres:15
    container_name: bms-postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - bms-net
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  backend:
    container_name: bms-backend
    build:
      context: ./src/backend
    ports:
      - "8080:8080"
    networks:
      - bms-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MQTT_BROKER_HOST_IP=${MQTT_BROKER_HOST_IP}
    depends_on:
      - mosquitto
      - influxdb
      - postgres

  mdns-repeater:
    image: raetha/mdns-repeater
    container_name: bms-mdns-repeater
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    environment:
      - EXTERNAL_INTERFACE=${EXTERNAL_INTERFACE}
      - DOCKER_NETWORK_NAME=${DOCKER_NETWORK_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Definiujemy naszą sieć wirtualną na najwyższym poziomie
networks:
  bms-net:
    name: ${DOCKER_NETWORK_NAME}
